const PRIMARY = '#2e7c31';
const PRIMARYLIGHT = '#60ac5d';
const PRIMARYTEXT = '#ffffff';
const SECONDARY = '#a0877e';
const SECONDARYLIGHT = '#d1b7ad';
const SECONDARYTEXT = '#000000';
export {
  PRIMARY, PRIMARYTEXT, PRIMARYLIGHT, SECONDARY, SECONDARYTEXT, SECONDARYLIGHT,
};
